### ISSUE TITLE
Mobile banner spacing and navbar cutoff

### ISSUE THREAD

**Issue by BK1031** [PennSpark/spark-website#6]
On mobile browsers, the banner text is pushed to the left and is cutting off the top navigation bar.

![image](https://github.com/PennSpark/spark-website/assets/33289435/64e03165-9aea-45e8-8bb9-8c3833b109df)

**Comment by Kashyap456** [comment]
![image](https://github.com/PennSpark/spark-website/assets/36755505/08cfec40-ef63-4a1e-91e2-e644d9d03130)

**Comment by Kashyap456** [comment]
![image](https://github.com/PennSpark/spark-website/assets/36755505/50bd3dc0-9b32-4081-86a9-a79a0f36853c)

**Comment by Kashyap456** [comment]
should be fixed after [pr](https://github.com/PennSpark/spark-website/tree/6-mobile-banner-spacing-and-navbar-cutoff) is merged

**Comment by BK1031** [comment]
W
